### ISSUE TITLE
iOS part does not work if info.plist files has been renamed.

### ISSUE THREAD

**Issue by gmhz** [Syed-Waleed-Shah/rename_app#1]
If iOS parts "info.plsit" file has been renamed it does not work.
For example from package https://pub.dev/packages/flutter_native_splash :
If you have changed the name(s) of your info.plist file(s), you can specify the filename(s) 
 with the info_plist_files parameter.  Remove only the # characters in the three lines below,
 do not remove any spaces:
info_plist_files:
 - 'ios/Runner/Info-Debug.plist'
 - 'ios/Runner/Info-Release.plist'
 
 And there could be more than 1 info.plist files

**Comment by Syed-Waleed-Shah** [comment]
Ok thanks for your findings. I will tackle this issue in next release.

**Comment by chandrabezzo** [comment]
Hi @gmhz have you check [package_rename_plus](https://pub.dev/packages/package_rename_plus)?

**Comment by Syed-Waleed-Shah** [comment]
> If iOS parts "info.plsit" file has been renamed it does not work. For example from package https://pub.dev/packages/flutter_native_splash : If you have changed the name(s) of your info.plist file(s), you can specify the filename(s) with the info_plist_files parameter. Remove only the # characters in the three lines below, do not remove any spaces: info_plist_files:
> 
> * 'ios/Runner/Info-Debug.plist'
> * 'ios/Runner/Info-Release.plist'
> 
> And there could be more than 1 info.plist files

Hi @gmhz  this issue is fixed. Closing this issue.
