### ISSUE TITLE
Non-ascii name is not supported

### ISSUE THREAD

**Issue by dbsxdbsx** [Syed-Waleed-Shah/rename_app#3]
When using the command `flutter pub run rename_app:main all="My App Name"`, if the `My App Name` is non-ascii chars like Chinese, then it would failed to build app.    Maybe this is not an package but flutter issue?

**Comment by waleed-brandverse** [comment]
Let me look into the issue. I will update you @dbsxdbsx

**Comment by Syed-Waleed-Shah** [comment]
> When using the command `flutter pub run rename_app:main all="My App Name"`, if the `My App Name` is non-ascii chars like Chinese, then it would failed to build app. Maybe this is not an package but flutter issue?

Let me look into this issue @dbsxdbsx. I will update you on this regard.

**Comment by Syed-Waleed-Shah** [comment]
> When using the command `flutter pub run rename_app:main all="My App Name"`, if the `My App Name` is non-ascii chars like Chinese, then it would failed to build app. Maybe this is not an package but flutter issue?

Hi @dbsxdbsx
Package is working fine on non-ascii characters such as Chinese. Here is screenshot from my side, Please close the ticket if you agree, otherwise show me the exact error you are encountering.
Example command: dart run rename_app:main all="諡號; 谥号"

![image](https://github.com/Syed-Waleed-Shah/rename_app/assets/55924255/c8939a37-74c8-445e-a387-3fb0bcf768a8)

**Comment by dbsxdbsx** [comment]
Thanks your feedback.  The issue I mean is not related to  renaming itself, but it doesn't make the building successful. 
For example, with this ` flutter pub run rename_app:main all="代理" `, it succeeded in renaming, but when building the app for targeting windows, it errors with this:
```
  features, such as generator expressions, and may result in undefined
  behavior.


CMake Error at CMakeLists.txt:41 (target_compile_features):
  Cannot specify compile features for target "代理" which is not built by
  this project.
Call Stack (most recent call first):
  runner/CMakeLists.txt:21 (apply_standard_settings)


CMake Error at runner/CMakeLists.txt:24 (target_compile_definitions):
  Cannot specify compile definitions for target "代理" which is not built
  by this project.


CMake Error at runner/CMakeLists.txt:25 (target_compile_definitions):
  Cannot specify compile definitions for target "代理" which is not built
  by this project.


CMake Error at runner/CMakeLists.txt:26 (target_compile_definitions):
  Cannot specify compile definitions for target "代理" which is not built
  by this project.


CMake Error at runner/CMakeLists.txt:27 (target_compile_definitions):
  Cannot specify compile definitions for target "代理" which is not built
  by this project.


CMake Error at runner/CMakeLists.txt:28 (target_compile_definitions):
  Cannot specify compile definitions for target "代理" which is not built
  by this project.


CMake Error at runner/CMakeLists.txt:31 (target_compile_definitions):
  Cannot specify compile definitions for target "代理" which is not built
  by this project.


CMake Error at runner/CMakeLists.txt:35 (target_link_libraries):
  Cannot specify link libraries for target "代理" which is not built by
  this project.


Error: Unable to generate build files

Exited (1).
```

**Comment by Syed-Waleed-Shah** [comment]
> Thanks your feedback. The issue I mean is not related to renaming itself, but it doesn't make the building successful. For example, with this `flutter pub run rename_app:main all="代理"`, it succeeded in renaming, but when building the app for targeting windows, it errors with this:
> 
> ```
>   features, such as generator expressions, and may result in undefined
>   behavior.
> 
> 
> CMake Error at CMakeLists.txt:41 (target_compile_features):
>   Cannot specify compile features for target "代理" which is not built by
>   this project.
> Call Stack (most recent call first):
>   runner/CMakeLists.txt:21 (apply_standard_settings)
> 
> 
> CMake Error at runner/CMakeLists.txt:24 (target_compile_definitions):
>   Cannot specify compile definitions for target "代理" which is not built
>   by this project.
> 
> 
> CMake Error at runner/CMakeLists.txt:25 (target_compile_definitions):
>   Cannot specify compile definitions for target "代理" which is not built
>   by this project.
> 
> 
> CMake Error at runner/CMakeLists.txt:26 (target_compile_definitions):
>   Cannot specify compile definitions for target "代理" which is not built
>   by this project.
> 
> 
> CMake Error at runner/CMakeLists.txt:27 (target_compile_definitions):
>   Cannot specify compile definitions for target "代理" which is not built
>   by this project.
> 
> 
> CMake Error at runner/CMakeLists.txt:28 (target_compile_definitions):
>   Cannot specify compile definitions for target "代理" which is not built
>   by this project.
> 
> 
> CMake Error at runner/CMakeLists.txt:31 (target_compile_definitions):
>   Cannot specify compile definitions for target "代理" which is not built
>   by this project.
> 
> 
> CMake Error at runner/CMakeLists.txt:35 (target_link_libraries):
>   Cannot specify link libraries for target "代理" which is not built by
>   this project.
> 
> 
> Error: Unable to generate build files
> 
> Exited (1).
> ```

Yes its the limitation of flutter framework which does not allow non ascii characters as app name. Closing the issue.
