### ISSUE TITLE
Renaming Does Not Work on Windows

### ISSUE THREAD

**Issue by Finnomator** [Syed-Waleed-Shah/rename_app#6]
According to [this](https://stackoverflow.com/questions/64800455/how-to-change-app-icon-and-app-name-for-flutter-desktop-application), not `windows/CMakeLists.txt` but `windows/runner/main.cpp` has to be changed in order to rename the app on Windows.

Also, changing the BINARY_NAME in `windows/CmakeLists.txt` causes the following build issue to occur:

```
Building Windows application...
CMake Error at runner/CMakeLists.txt:9 (add_executable):
  The target name "X X X" is reserved or not valid for certain
  CMake features, such as generator expressions, and may result in undefined
  behavior.


CMake Error at CMakeLists.txt:41 (target_compile_features):
  Cannot specify compile features for target "X X X" which is not
  built by this project.
Call Stack (most recent call first):
  runner/CMakeLists.txt:21 (apply_standard_settings)

.
.
.

Error: Unable to generate build files
```

**Comment by Syed-Waleed-Shah** [comment]
> According to [this](https://stackoverflow.com/questions/64800455/how-to-change-app-icon-and-app-name-for-flutter-desktop-application), not `windows/CMakeLists.txt` but `windows/runner/main.cpp` has to be changed in order to rename the app on Windows.
> 
> Also, changing the BINARY_NAME in `windows/CmakeLists.txt` causes the following build issue to occur:
> 
> ```
> Building Windows application...
> CMake Error at runner/CMakeLists.txt:9 (add_executable):
>   The target name "X X X" is reserved or not valid for certain
>   CMake features, such as generator expressions, and may result in undefined
>   behavior.
> 
> 
> CMake Error at CMakeLists.txt:41 (target_compile_features):
>   Cannot specify compile features for target "X X X" which is not
>   built by this project.
> Call Stack (most recent call first):
>   runner/CMakeLists.txt:21 (apply_standard_settings)
> 
> .
> .
> .
> 
> Error: Unable to generate build files
> ```

Ok, I will look into this issue ASAP.

**Comment by Finnomator** [comment]
@Syed-Waleed-Shah if you are currently not working on this I can fix it.

**Comment by Syed-Waleed-Shah** [comment]
> @Syed-Waleed-Shah if you are currently not working on this I can fix it.

It would be appreciated if you could fix this :) @Finnomator
