### ISSUE TITLE
Whitespaces inconsistency

### ISSUE THREAD

**Issue by sydneyagcaoili** [Syed-Waleed-Shah/rename_app#9]
I like this package coz it's brilliant. It would be nice if there's an option where it wouldnt mess up the whitespaces of some of the files.

**Comment by Syed-Waleed-Shah** [comment]
> I like this package coz it's brilliant. It would be nice if there's an option where it wouldnt mess up the whitespaces of some of the files.

Can you please explain the issue? It would be great if you share the issue you are facing regarding white spaces.

**Comment by sydneyagcaoili** [comment]
Sorry about that, it's when the AndroidManifest.xml and Info.plist.. The whitespaces are being modified, the xml items are being rearranged, due to the xml/plist package + pretty print. It kinda interferes with the intended code formatting of some developers.

**Comment by Syed-Waleed-Shah** [comment]
> Sorry about that, it's when the AndroidManifest.xml and Info.plist.. The whitespaces are being modified, the xml items are being rearranged, due to the xml/plist package + pretty print. It kinda interferes with the intended code formatting of some developers.

It seems the issue is related to the framework instead of this package.
